import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` h-full antialiased bg-white`}>
      <body className="min-h-full flex flex-col bg-white">{children}</body>
    </html>
  );
}
